version: "3.9"

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432

    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
